### ISSUE TITLE
Criar splash screen

### ISSUE THREAD

**Issue by carloscdias** [midianinja/AppNinja#22]
Criar splash screen com a logo do Midia Ninja na tela inicial

**Comment by gitrickmachado** [comment]
Criado! 
Uma dúvida:
Conseguem reproduzir por meio de código o padrão de carregamento que criei na splash?

![inkedsplash_screen_li](https://user-images.githubusercontent.com/45082862/48662343-066b6500-ea68-11e8-8384-ef6208a2b9ca.jpg)
