### ISSUE TITLE
Tela do Perfil Ninja

### ISSUE THREAD

**Issue by carloscdias** [midianinja/AppNinja#29]
# Objetivo

Criar uma tela seguindo o padrão de layout e desenvolvimento para visualização e edição dos campos da tabela do perfil ninja.
Validar campos e submeter para o backend.
Atualizar as informações do usuário ou informa-lo em caso de erro.

**Comment by lpirola** [comment]
@carloscdias gostei da solução. Chegou criou um link no expo.io com um build já feito? E ainda está desenvolvendo algo que precisa de ajuda para aprovar o PR?

**Comment by carloscdias** [comment]
@lpirola Ainda não temos uma build publicada no expo.io, mas esse pode ser o nosso próximo passo :)
Toda ajuda é bem vinda para o projeto. Acho que o @luisfcosta2015 e a @BrancaSchulz podem dar uma moral com isso
