### ISSUE TITLE
Desenvolvimento: Finalizar backend

### ISSUE THREAD

**Issue by luisfcosta2015** [midianinja/AppNinja#42]

**Comment by leonardoaj** [comment]
Fala ai galera, beleza? Ao meu ver, o MVP pro backend vai ter somente as funcionalidades relacionadas a criação do usuário e criação do perfil ninja, certo? Criei um projeto chamado "dev backend" pra ficar com os cards dessas histórias, assim podemos especificar melhor as funcionalidades que fazem parte dessas issues e ainda saber o que tá sendo feito, o que foi feito e o que ainda tem pra se fazer.

**Comment by carloscdias** [comment]
Boa @leonardoaj ! 👍 💯
