### ISSUE TITLE
Modelar interesses

### ISSUE THREAD

**Issue by leonardoaj** [midianinja/AppNinja#48]
O que são interesses? Quais são os atributos? Somente texto  descritivo mesmo?

**Comment by BrancaSchulz** [comment]
Podemos fazer uma lista de interesses como:

1. Articulação Política 
2. Sustentabilidade 
3. Formação Livre 
4. Comunicação 
5. Linguagens (fotografia, audiovisual, design) 
6. Tecnologia
7. Criar núcleo de midiativismo na minha cidade
8. Doar tempo por meio de trabalho remoto ou presencial 
9. Colaborar com projetos a partir de minhas habilidades 
10. Divulgar conteúdos nas minhas redes sociais e outros meios que articulo/faço parte
11. Realizar ações e eventos em rede
12. Realizar campanha
13. Outros
