### ISSUE TITLE
Usuário e senha do e-mail estão versionados no GitHub

### ISSUE THREAD

**Issue by newtonbeck** [midianinja/AppNinja#59]
## Problema
Usuário e senha do e-mail estão versionados no GitHub, no arquivo abaixo:

https://github.com/midianinja/AppNinja/blob/6bb8befdc7e4d2776c5dd51b204c7948e8e9bd48/backend/backend/settings.py

**Comment by lpirola** [comment]
@newtonbeck fiz o PR #61 que resolve o problema!
